project_id = "dutkpzrisvqgxadxbkxo"

[functions.fetch-leagues]
verify_jwt = false

[functions.fetch-fixtures]
verify_jwt = false

[functions.analyze-fixture]
verify_jwt = true

[functions.fetch-odds]
verify_jwt = true

[functions.filterizer-query]
verify_jwt = true

[functions.stats-refresh]
verify_jwt = true

[functions.calculate-value]
verify_jwt = true

[functions.generate-ticket]
verify_jwt = true

[functions.fetch-odds-bets]
verify_jwt = true

[functions.optimize-selections-refresh]
verify_jwt = true

[functions.backfill-odds]
verify_jwt = true
